name: Obfuscate JavaScript
on: push

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install javascript-obfuscator
        run: npm install javascript-obfuscator

      - name: Obfuscate JS
        run: |
          npx javascript-obfuscator js/your-script.js --output js/obfuscated.js \
            --compact true \
            --control-flow-flattening true \
            --dead-code-injection true \
            --debug-protection true \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --self-defending true \
            --string-array true \
            --string-array-encoding rc4,base64

      - name: Commit Obfuscated File
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add js/obfuscated.js
          git commit -m "Auto-obfuscated JS"
          git push
